FROM openjdk:11-jre

ARG DB_KEY
ARG KAKAO_ID
ARG REDIRECT_URL
ARG KAKO_SCOPE
ARG AUTH_KEY

ENV DB_KEY=$DB_KEY
ENV KAKAO_ID=$KAKAO_ID
ENV REDIRECT_URL=$REDIRECT_URL
ENV KAKO_SCOPE=$KAKO_SCOPE
ENV AUTH_KEY=$AUTH_KEY

COPY build/libs/keki-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
